# Generated by Django 3.0.6 on 2020-07-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('username', models.CharField(max_length=128)),
                ('birthday', models.CharField(max_length=64)),
                ('grade', models.CharField(max_length=16)),
                ('identity', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'user_table',
            },
        ),
    ]
